
[font]
size = 9

[keyboard]
bindings = [
    # tmux conflict
    { key = "-", mods = "Control", action = "None" },
    { key = "=", mods = "Control", action = "None" }
]

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[general]
live_config_reload = true
import = ["colors.toml"]

[window]
opacity = 0.88
decorations = "none"
dynamic_padding = true

[window.padding]
y = 10
